FROM python:3.10

RUN apt update && apt install -y curl

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHON UNBUFFERED=1

COPY ./requirements.txt /home/
RUN pip3 install --no-cache-dir --upgrade -r /home/requirements.txt

COPY ./backend /home/backend
COPY ./netology_pd_diplom /home/netology_pd_diplom

WORKDIR /home

RUN chown -R nobody:nogroup /home

CMD celery -A netology_pd_diplom worker -l info --uid=nobody --gid=nogroup