version: '3.1'

networks:
  product-network:

services:
  db:
    image: postgres:14.6-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5435:5432"
    networks:
      product-network:
        aliases:
          - ${PG_HOST}
