# Generated by Django 4.1.5 on 2023-01-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=40, verbose_name='Отчество'),
        ),
    ]
